name: CI/CD Pipeline (Web App)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/elias-portfolio:latest apps/web

      # 4️⃣ Log in to Docker Hub
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push your-dockerhub-username/elias-portfolio:latest

      # 6️⃣ Add VPS and Pi host keys to known_hosts
      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.PI_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      # 7️⃣ Deploy Docker image on Pi via VPS
      - name: Deploy on Pi
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa \
              -o ProxyJump=root@${{ secrets.VPS_HOST }} \
              ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "
                docker pull your-dockerhub-username/elias-portfolio:latest &&
                docker compose down &&
                docker compose up -d --build
          "
