name: CI/CD Pipeline (Web App)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t eliasbe123/elias-portfolio:latest apps/web

      # 4️⃣ Log in to Docker Hub
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push eliasbe123/elias-portfolio:latest

      # 6️⃣ Add VPS and Pi host keys to known_hosts
      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.PI_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      # 7️⃣ Deploy Docker image on Pi via VPS
      - name: Deploy Docker on Pi via VPS
        run: |
          set -x
      
          # 1️⃣ Start SSH agent and add private key
          eval "$(ssh-agent -s)"
          echo "${{ secrets.PI_SSH_KEY }}" | tr -d '\r' | ssh-add -
          
          # 2️⃣ Prepare SSH directory and known_hosts for VPS
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
      
          # 3️⃣ Test VPS connectivity
          echo "Testing connection to VPS..."
          ssh -A -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} "echo 'Connected to VPS'"
      
          # 4️⃣ Test Pi connectivity through ProxyJump
          echo "Testing connection to Pi via VPS..."
          ssh -A -o StrictHostKeyChecking=no -J root@${{ secrets.VPS_HOST }} ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "echo 'Connected to Pi'"
      
          # 5️⃣ Deploy Docker image
          echo "Deploying Docker image on Pi..."
          ssh -A -o StrictHostKeyChecking=no -J root@${{ secrets.VPS_HOST }} ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "
            set -x
            cd ~/deploy || mkdir -p ~/deploy && cd ~/deploy
            docker pull eliasbe123/elias-portfolio:latest
            docker compose down
            docker compose up -d
          "
